version: "3.9"
services:
  backend:
    build: ./server
    ports: [ "8080:8080" ]
    environment:
      - AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - CLIENT_ORIGINS=${CLIENT_ORIGINS}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PARAMETER_PREFIX=${PARAMETER_PREFIX}
      - S3_BUCKET=${S3_BUCKET}
      - DYNAMO_TABLE=${DYNAMO_TABLE}
      - ELASTICACHE_ENDPOINT=${ELASTICACHE_ENDPOINT}
      - EC2_INSTANCE_ID=${EC2_INSTANCE_ID}
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
      - EC2_PUBLIC_DNS=${EC2_PUBLIC_DNS}
  frontend:
    build: ./client
    ports: [ "3000:80" ]
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - VITE_EC2_INSTANCE_ID=${EC2_INSTANCE_ID}
      - VITE_EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
    depends_on:
      - backend
